name: ftp-site
on:
  workflow_dispatch:
  push:
    paths:
      - "sites/**"
jobs:
  ftp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lftp mirror
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
          FTP_REMOTE_DIR: ${{ secrets.FTP_REMOTE_DIR }}
        run: |
          sudo apt-get update -y && sudo apt-get install -y lftp
          lftp -c "open -u $FTP_USER,$FTP_PASS $FTP_HOST; mirror -R --verbose ./sites ${FTP_REMOTE_DIR:-/public_html}"
